### ISSUE TITLE
Error when exporting file activity when no description entered

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/moodle-block_oppia_mobile_export#131]
Error actually happens on upload to Oppia server - but should be fixed in the export process - and update the XML schema to make sure either the description is optional - or it's never non-empty

**Comment by jjoseba** [comment]
In the server side the error is taken care of. Right now, in the XML schema is already optional, the problem is that in the export process, and empty `<description />` tag is created when it is empty. Which approach do you prefer? I think that better than to force the user to introduce a description for every activity, is to check in the export process and don't generate an empty description.

**Comment by alexlittle** [comment]
Thanks - Yes I agree it is better to require a description during the export process. Since (currently at least) the description is unused in Oppia, if there is an empty description, then just use the activity name/title.

FYI I think Moodle used to require the description for all activities, so wasn't an issue before, but in more recent versions it's no longer required.
