### ISSUE TITLE
Dependencies check failed for block_oppia_mobile_export

### ISSUE THREAD

**Issue by Ihedibamoses** [DigitalCampus/moodle-block_oppia_mobile_export#183]
i successfully installed the moodle server online with a hosting company but the oppia_mobile_export faile to install... with an error message :"Dependencies check failed for block_oppia_mobile_export"

**Comment by alexlittle** [comment]
Hi Moses,
Few things to check here:

1) the directory for the block must be exactly "oppia_mobile_export" (within the moodle blocks directory)
2) Have a look at the Moodle server info page (in the admin section: http://<your_moodle_domain_name>/admin/environment.php) to check all the plugins (dependencies) have status as 'OK'
3) What version of Moodle is it? the block only works with v3.1+ - since all previous versions of Moodle are now unsupported by Moodle team.

Hope that helps.
A

**Comment by Ihedibamoses** [comment]
I was even going to send you another email now...I just discovered the
version of block isn't the same as the one provided by our hosting server.

So is there any way you can assist in providing a version equivalent to 2.6
Moodle version.

Thank you.

**Comment by alexlittle** [comment]
Moodle 2.6 is very old now - Moodle themselves haven;t provided bug or security fixes for this version since May 2015 (see: https://docs.moodle.org/dev/Releases)
I'd suggest installing your own Moodle (on an AWS machine) so then you can have the most recent version and have full control over it.
If you really really want to use 2.6  then you can use an old version of the block - but we won;t be able to provide any help/support for this and it will be missing features/fixes etc that are in the up to date version.

Cheers,
A
